# Generated by Django 6.1.1 on 2026-10-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acomodacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_acomodacao', models.CharField(max_length=100)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_quartos', models.PositiveIntegerField(default=0)),
                ('qtd_banheiros', models.PositiveIntegerField(default=0)),
                ('qtd_camas', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
