# Generated by Django 6.1.1 on 2026-10-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomodacao',
            name='max_hospedes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='acomodacao',
            name='status_hospedagem',
            field=models.BooleanField(default=True),
        ),
    ]
