# Generated by Django 6.1.1 on 2026-10-09 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacoes', '0002_acomodacao_max_hospedes_acomodacao_status_hospedagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acomodacao',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acomodacoes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
