# Generated by Django 6.1.1 on 2026-10-09 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacoes', '0003_acomodacao_proprietario'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acomodacao',
            name='hospedes',
            field=models.ManyToManyField(related_name='acomodacoes_reservadas', through='reservas.Reserva', to=settings.AUTH_USER_MODEL),
        ),
    ]
