# Generated by Django 6.1.1 on 2026-10-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacoes', '0004_acomodacao_hospedes'),
        ('reservas', '0001_initial'),
        ('usuarios', '0002_alter_usuario_cpf_alter_usuario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acomodacao',
            field=models.ManyToManyField(related_name='acomodacoes_reservadas', through='reservas.Reserva', to='acomodacoes.acomodacao'),
        ),
    ]
